//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34003
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WP8Nico.nomula.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WP8Nico.nomula.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About this app に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add to My List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add to the following My List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddTargetMylist {
            get {
                return ResourceManager.GetString("AddTargetMylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add to My List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddToMylist {
            get {
                return ResourceManager.GetString("AddToMylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Account is not set. Move to the account setting page? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AskLogin {
            get {
                return ResourceManager.GetString("AskLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Author: Daisuke Nomura に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play the video automatically. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoPlay {
            get {
                return ResourceManager.GetString("AutoPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot Add to {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CannotAddMylist {
            get {
                return ResourceManager.GetString("CannotAddMylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot play に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CannotPlay {
            get {
                return ResourceManager.GetString("CannotPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FLV movie に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CannotPlayFLV {
            get {
                return ResourceManager.GetString("CannotPlayFLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot play FLV movie. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CannotPlayFLVDesc {
            get {
                return ResourceManager.GetString("CannotPlayFLVDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SWF movie に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CannotPlaySWF {
            get {
                return ResourceManager.GetString("CannotPlaySWF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot play SWF movie. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CannotPlaySWFDesc {
            get {
                return ResourceManager.GetString("CannotPlaySWFDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot play this movie on this app. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CannotPlayThisApp {
            get {
                return ResourceManager.GetString("CannotPlayThisApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CannotPlayUnknown {
            get {
                return ResourceManager.GetString("CannotPlayUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This movie is Unknown Content. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CannotPlayUnknownDesc {
            get {
                return ResourceManager.GetString("CannotPlayUnknownDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Category に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Daily: All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryTypeDailyAll {
            get {
                return ResourceManager.GetString("CategoryTypeDailyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Daily: My Listed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryTypeDailyMylist {
            get {
                return ResourceManager.GetString("CategoryTypeDailyMylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Daily: Comments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryTypeDailyRes {
            get {
                return ResourceManager.GetString("CategoryTypeDailyRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Daily: Views に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryTypeDailyView {
            get {
                return ResourceManager.GetString("CategoryTypeDailyView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hourly: All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryTypeHourlyAll {
            get {
                return ResourceManager.GetString("CategoryTypeHourlyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hourly: My Listed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryTypeHourlyMylist {
            get {
                return ResourceManager.GetString("CategoryTypeHourlyMylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hourly: Comments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryTypeHourlyRes {
            get {
                return ResourceManager.GetString("CategoryTypeHourlyRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hourly: Views に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryTypeHourlyView {
            get {
                return ResourceManager.GetString("CategoryTypeHourlyView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monthly: All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryTypeMonthlyAll {
            get {
                return ResourceManager.GetString("CategoryTypeMonthlyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monthly: My Listed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryTypeMonthlyMylist {
            get {
                return ResourceManager.GetString("CategoryTypeMonthlyMylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monthly: Comments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryTypeMonthlyRes {
            get {
                return ResourceManager.GetString("CategoryTypeMonthlyRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monthly: Views に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryTypeMonthlyView {
            get {
                return ResourceManager.GetString("CategoryTypeMonthlyView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total: All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryTypeTotalAll {
            get {
                return ResourceManager.GetString("CategoryTypeTotalAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total: My Listed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryTypeTotalMylist {
            get {
                return ResourceManager.GetString("CategoryTypeTotalMylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total: Comments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryTypeTotalRes {
            get {
                return ResourceManager.GetString("CategoryTypeTotalRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total: Views に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryTypeTotalView {
            get {
                return ResourceManager.GetString("CategoryTypeTotalView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Weekly: All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryTypeWeeklyAll {
            get {
                return ResourceManager.GetString("CategoryTypeWeeklyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Weekly: My Listed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryTypeWeeklyMylist {
            get {
                return ResourceManager.GetString("CategoryTypeWeeklyMylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Weekly: Comments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryTypeWeeklyRes {
            get {
                return ResourceManager.GetString("CategoryTypeWeeklyRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Weekly: Views に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryTypeWeeklyView {
            get {
                return ResourceManager.GetString("CategoryTypeWeeklyView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Caution: This app is unofficial application. Don&apos;t ask this app to the support office on niconico. If you switch on the Suggest feature of nicosearch, input word is sent to the server nicosearch. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Caution {
            get {
                return ResourceManager.GetString("Caution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input your niconico account. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CautionAccount {
            get {
                return ResourceManager.GetString("CautionAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommentCount {
            get {
                return ResourceManager.GetString("CommentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete the search history. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteSearchHistory {
            get {
                return ResourceManager.GetString("DeleteSearchHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete the watch history. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteWatchedHistory {
            get {
                return ResourceManager.GetString("DeleteWatchedHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description: This app is a viewer for niconico. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DetailDescription {
            get {
                return ResourceManager.GetString("DetailDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GoHome {
            get {
                return ResourceManager.GetString("GoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   H.264 Low Quality Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string H264LowQuality {
            get {
                return ResourceManager.GetString("H264LowQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   H.264 Streaming  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string H264SingleStreaming {
            get {
                return ResourceManager.GetString("H264SingleStreaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sync the history to music+videos hub. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HubHistorySave {
            get {
                return ResourceManager.GetString("HubHistorySave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   info に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show anonymous (184) comments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IYAYO {
            get {
                return ResourceManager.GetString("IYAYO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日本語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Link に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginFalse {
            get {
                return ResourceManager.GetString("LoginFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-mail address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MailAddress {
            get {
                return ResourceManager.GetString("MailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Videos to My List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mylist {
            get {
                return ResourceManager.GetString("Mylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   my list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mylist2 {
            get {
                return ResourceManager.GetString("Mylist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My Lists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MylistCount {
            get {
                return ResourceManager.GetString("MylistCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My Uploads に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MyUploads {
            get {
                return ResourceManager.GetString("MyUploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name: ニコアプリ(仮) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect to niconico Mobile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NicoDougaMobile {
            get {
                return ResourceManager.GetString("NicoDougaMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Suggest words by nicosearch. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NicosearchSuggest {
            get {
                return ResourceManager.GetString("NicosearchSuggest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not set niconico Account. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotSetAccount {
            get {
                return ResourceManager.GetString("NotSetAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only for Premium Members に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OnlyforPremiumMember {
            get {
                return ResourceManager.GetString("OnlyforPremiumMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   post に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PostedTime {
            get {
                return ResourceManager.GetString("PostedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   my uploads に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PostedVideo {
            get {
                return ResourceManager.GetString("PostedVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Post a message に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PostMessage {
            get {
                return ResourceManager.GetString("PostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   public に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PublicMylist {
            get {
                return ResourceManager.GetString("PublicMylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ranking に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ranking {
            get {
                return ResourceManager.GetString("Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   related に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string related {
            get {
                return ResourceManager.GetString("related", resourceCulture);
            }
        }
        
        /// <summary>
        ///   reload に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeat playback. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RepeatVideo {
            get {
                return ResourceManager.GetString("RepeatVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LeftToRight に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   en に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search2 {
            get {
                return ResourceManager.GetString("Search2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyword: Few comments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchKeywordCommentLittle {
            get {
                return ResourceManager.GetString("SearchKeywordCommentLittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyword: Many comments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchKeywordCommentMany {
            get {
                return ResourceManager.GetString("SearchKeywordCommentMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyword: New comments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchKeywordCommentNew {
            get {
                return ResourceManager.GetString("SearchKeywordCommentNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyword: Old comments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchKeywordCommentOld {
            get {
                return ResourceManager.GetString("SearchKeywordCommentOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyword: Long duration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchKeywordLengthLong {
            get {
                return ResourceManager.GetString("SearchKeywordLengthLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyword: Short duration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchKeywordLengthShort {
            get {
                return ResourceManager.GetString("SearchKeywordLengthShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyword: Least My Listed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchKeywordMylistLittle {
            get {
                return ResourceManager.GetString("SearchKeywordMylistLittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyword: Most My Listed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchKeywordMylistMany {
            get {
                return ResourceManager.GetString("SearchKeywordMylistMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyword: Newest Uploads に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchKeywordNewAsc {
            get {
                return ResourceManager.GetString("SearchKeywordNewAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyword: Oldest Uploads に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchKeywordNewDesc {
            get {
                return ResourceManager.GetString("SearchKeywordNewDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyword: Least Viewed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchKeywordViewLittle {
            get {
                return ResourceManager.GetString("SearchKeywordViewLittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyword: Most Viewed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchKeywordViewMany {
            get {
                return ResourceManager.GetString("SearchKeywordViewMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tag: Few comments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchTagCommentLittle {
            get {
                return ResourceManager.GetString("SearchTagCommentLittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tag: Many comments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchTagCommentMany {
            get {
                return ResourceManager.GetString("SearchTagCommentMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tag: New comments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchTagCommentNew {
            get {
                return ResourceManager.GetString("SearchTagCommentNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tag: Old comments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchTagCommentOld {
            get {
                return ResourceManager.GetString("SearchTagCommentOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tag: Long duration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchTagLengthLong {
            get {
                return ResourceManager.GetString("SearchTagLengthLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tag: Short duration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchTagLengthShort {
            get {
                return ResourceManager.GetString("SearchTagLengthShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tag: Least My Listed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchTagMylistLittle {
            get {
                return ResourceManager.GetString("SearchTagMylistLittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tag: Most My Listed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchTagMylistMany {
            get {
                return ResourceManager.GetString("SearchTagMylistMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tag: Newest Uploads に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchTagNewAsc {
            get {
                return ResourceManager.GetString("SearchTagNewAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tag: Oldest Uploads に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchTagNewDesc {
            get {
                return ResourceManager.GetString("SearchTagNewDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tag: Least Viewed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchTagViewLittle {
            get {
                return ResourceManager.GetString("SearchTagViewLittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tag: Most Viewed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchTagViewMany {
            get {
                return ResourceManager.GetString("SearchTagViewMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Would you like to add Videos to My List? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectMylist {
            get {
                return ResourceManager.GetString("SelectMylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Share に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Synchronized Viewing History に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShareWatched {
            get {
                return ResourceManager.GetString("ShareWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   synchronized viewing history に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShareWatched2 {
            get {
                return ResourceManager.GetString("ShareWatched2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sort に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot play FLV format. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SoundOnly {
            get {
                return ResourceManager.GetString("SoundOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tags に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quicklist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToriaezuMylist {
            get {
                return ResourceManager.GetString("ToriaezuMylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This video is Premium members only. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnavailableForNotPremium {
            get {
                return ResourceManager.GetString("UnavailableForNotPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undefined movie に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UndefinedMovie {
            get {
                return ResourceManager.GetString("UndefinedMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version: 0.25 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VideoLength {
            get {
                return ResourceManager.GetString("VideoLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Views に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewCount {
            get {
                return ResourceManager.GetString("ViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Viewing History に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Watched {
            get {
                return ResourceManager.GetString("Watched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   viewing history に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Watched2 {
            get {
                return ResourceManager.GetString("Watched2", resourceCulture);
            }
        }
    }
}
